Syslog
| where Facility in ("auth", "authpriv")
| where SyslogMessage contains "Invalid user" or SyslogMessage contains "Failed password" or SyslogMessage contains "from"
| extend SourceIP = extract(@"from ((?:\d{1,3}\.){3}\d{1,3})", 1, SyslogMessage)
| where isnotempty(SourceIP)
| summarize Attempts = count() by SourceIP
| sort by Attempts desc

//Used KQL to show SourceIP and the number of attempts to log into the Virtual Machine
